### ISSUE TITLE
Maintain comments on a single line 

### ISSUE THREAD

**Issue by joshprice** [bradymholt/vscode-pgFormatter#12]
Whole line comments should be preserved on a single line and not indented. eg:

```sql
SELECT
  *
FROM
  users
-- WHERE
--  name = 'abc'
;
```

is incorrectly formatted as

```sql
SELECT
  *
FROM
  users -- WHERE
  --  name = 'abc'
;
```

Expect that comments on their own line inside a query should remain on their own line. Inline comments should remain inline.

**Comment by bradymholt** [comment]
Can you please report this on the pgFormatter repository.  My extension is a wrapper for this utility.
https://github.com/darold/pgFormatter
