### ISSUE TITLE
add -t option for policy formatting

### ISSUE THREAD

**Issue by pyramation** [bradymholt/vscode-pgFormatter#13]
Thanks for the great plugin! Just FYI, @darold updated `pgFormatter` to have a new option to format policies. Would be wonderful to add this in as a settings option.

https://github.com/darold/pgFormatter/issues/75#issuecomment-443370131

**Comment by bradymholt** [comment]
I don't have time to do this currently but would welcome a PR.

**Comment by pyramation** [comment]
sure happy to work on that - any tips or instructions on how to start? 

Even a high level description of what to do would be super helpful!

**Comment by bradymholt** [comment]
Version 1.6.2 was just published and supports this via the `formatType` setting.
