### ISSUE TITLE
Decimal type with unnecassary newline

### ISSUE THREAD

**Issue by derkan** [bradymholt/vscode-pgFormatter#16]
Hi,
```sql
"period_1_price" decimal (18,4) DEFAULT 0.0 NOT NULL
```
is formatted as:
```sql
"period_1_price" decimal (18,
        4) DEFAULT 0.0 NOT NULL,
```
as divided to new line before currency length.

**Comment by bradymholt** [comment]
This extension is a wrapper around https://github.com/darold/pgFormatter.  Please file formatting issues on that repository.  I will update the README here to try and make that clearer.
