### ISSUE TITLE
Can't locate pgFormatter/CLI

### ISSUE THREAD

**Issue by Borvik** [bradymholt/vscode-pgFormatter#17]
- [x] This is not an issue related to formatting of SQL itself.  (For formatting problems, an [issue should be created in the pgFormatter repository](https://github.com/darold/pgFormatter)).

```
ERROR: Error: Command failed: perl C:\Users\user1\.vscode\extensions\bradymholt.pgformatter-1.6.5\node_modules\psqlformat\vendor\pgFormatter\pg_format  --spaces 2 --comma-end --function-case 0 --keyword-case 2
Uncaught exception: Can't locate pgFormatter/CLI.pm in @INC (you may need to install the pgFormatter::CLI module) (@INC contains: /c/Users/user1/AppData/Local/Programs/Microsoft VS Code/lib /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at C:\Users\user1\.vscode\extensions\bradymholt.pgformatter-1.6.5\node_modules\psqlformat\vendor\pgFormatter\pg_format line 45.
 at C:\Users\user1\.vscode\extensions\bradymholt.pgformatter-1.6.5\node_modules\psqlformat\vendor\pgFormatter\pg_format line 19.
	main::__ANON__("Can't locate pgFormatter/CLI.pm in \@INC (you may need to inst"...) called at C:\Users\user1\.vscode\extensions\bradymholt.pgformatter-1.6.5\node_modules\psqlformat\vendor\pgFormatter\pg_format line 45
```

**Comment by bradymholt** [comment]
Cannot repo.  Tested in Windows 10 with VSCode 1.31.1 installed and it formatted a SQL document properly.  You might want to ensure perl is properly installed.

**Comment by Borvik** [comment]
Oops... That may be it.  I missed the Perl requirement in the readme.

**Comment by GabenGar** [comment]
I have the same error on windows 10 vscode 1.65.2. However I do have perl installed (strawberry distro), since `perl --version` works just fine in the same shell which invokes `code`.

**Comment by Owlpig** [comment]
Same issue as @GabenGar. `perl --version` works fine, windows 10 vscode 1.70.02

**Comment by bradymholt** [comment]
I won't be able to look into this one so if someone here is able to get to the root cause please post back to let others know what you found.

**Comment by GabenGar** [comment]
The strange thing is this problem resolved by itself for me. So I don't even know what is supposed to be done to fix it. 
It could be related to account permissions on which vscode is ran. Now that I think about it, `perl --version` was run in under the root user (I had some problems related to starting a node server in non-root), but VSCode was ran on non-root. Probably `perl` was in the `$PATH` for one account, but not the other.
