### ISSUE TITLE
Support "Format selection…"

### ISSUE THREAD

**Issue by bradleyayers** [bradymholt/vscode-pgFormatter#18]
- [x] This is not an issue related to formatting of SQL itself.  (For formatting problems, an [issue should be created in the pgFormatter repository](https://github.com/darold/pgFormatter)).

It'd be great to support a "Format selection…" command, so that SQL embedded in other languages (e.g. in JavaScript) can be formatted without needing to copy the SQL into a separate file, set the language to SQL, then run format document.

I see that the SQLTools extension has a feature like this, but unfortunately the formatter used by that plugin doesn't work well for pg.

**Comment by bradymholt** [comment]
Thanks for the issue.  I agree, this would be nice but I do not have time currently to implement this.  I am going to close for now but would welcome a future PR to implement this.
