### ISSUE TITLE
Formatting statements strangely

### ISSUE THREAD

**Issue by Globegitter** [bradymholt/vscode-pgFormatter#2]
First of all, I was super happy to see there is a pg formatter for vs code, but for some reason it seems to format my create table statements strangely.

Before formatting:
```
CREATE TABLE debtor (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v1(),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT clock_timestamp(),
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT clock_timestamp(),
    person_id   UUID,
);
```

After:

```
CREATE TABLE debtor (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v1 (),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT clock_timestamp(), updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT clock_timestamp(), person_id UUID,);
```

Making it in my opinion more unreadable. Is this as intendent?

Also it would be nice to have the option to have no spacing between function name and the brackets, i.e. keeping `uuid_generate_v1()` as it is.

Also creating trigger seems to me made a bit more unreadable:

Before:
```
CREATE TRIGGER update_timestamp
BEFORE UPDATE ON my_long_table_name
FOR EACH ROW EXECUTE PROCEDURE trigger_update_timestamp();
```

After:
```
CREATE TRIGGER update_timestamp BEFORE
UPDATE
    ON my_long_table_name FOR EACH ROW EXECUTE PROCEDURE trigger_update_timestamp ();
```

Here it is mostly just that last long line, which makes the statement more difficult to read imo.

**Comment by bradymholt** [comment]
Please report on [pgFormatter repository](https://github.com/darold/pgFormatter).  This extension is a wrapper for that utility.  I'd be glad to incorporate any updates to pgFormatter.
