### ISSUE TITLE
pgFormatter formatting bugfix adoption

### ISSUE THREAD

**Issue by jjangga0214** [bradymholt/vscode-pgFormatter#22]
- [x] This is not an issue related to formatting of SQL itself.  (For formatting problems, an [issue should be created in the pgFormatter repository](https://github.com/darold/pgFormatter)).

Hi, thank you for creating and maintaining this convenient tool! 

There is a formatting issue <https://github.com/darold/pgFormatter/issues/134>, and @darold resolved it. 

Can I ask when this fix would be reflected on vscode-pgFormatter?

**Comment by bradymholt** [comment]
The latest pgFormatter release is [4.0](https://github.com/darold/pgFormatter/releases).  As soon as another release is published it could be incorporated.  Something that would help me out is reaching out to Darold re: release and then posting back here once a new one is ready.

**Comment by bradymholt** [comment]
Version 1.8.0 should have this fix, as it uses pgFormatter 4.1: https://marketplace.visualstudio.com/items?itemName=bradymholt.pgformatter
