### ISSUE TITLE
Formatting document for psql files

### ISSUE THREAD

**Issue by Globegitter** [bradymholt/vscode-pgFormatter#3]
I have the extension https://github.com/doublefint/vscode-pgsql installed, which adds a new `psql` file association with slightly better highlighting. Would be great if it was possible to this extension as a formatter for that file type also.

**Comment by bradymholt** [comment]
Is the file extension handling you want psql or pgsql?  It looks like pgsql, right?  If so, this PR introduces that: https://github.com/bradymholt/vscode-pgFormatter/pull/5
