### ISSUE TITLE
the extension doesn't work in VS Code on windows

### ISSUE THREAD

**Issue by betfix** [bradymholt/vscode-pgFormatter#34]
On Windows, I installed pgFormatter in VSCode and added the following in settings.json:
```
"files.associations": {
		"*.pgsql": "sql"
  },
  "pgFormatter.perlBinPath": "C:\\Program Files\\Git\\usr\\bin\\perl.exe",
  "[sql]": {
    "editor.defaultFormatter": "bradymholt.pgformatter"
  }
```

On command line, perl --version outputs:
This is perl 5, version 24, subversion 1 (v5.24.1) built for x86_64-msys-thread-multi

But when I open either my.sql or my.pgsql file, right click and choose Format Document, nothing happens, code remains unformatted. (the same code formats well in the online pgFormatter tool)

I tried with "PostgreSQL" by Chris Kolkman and "Prettier" extensions enabled and disabled but the result is the same.

Any idea why it doesn't work?

**Comment by woss** [comment]
yep, even on WSL still is complaining the `There is no formatter for 'plsql' files installed.` and i can't find any debug info

**Comment by bradymholt** [comment]
@woss - This extension registers itself as a formatter for [.sql and .pgsql files](https://github.com/vemoo/vscode-pgFormatter/blob/master/src/extension.ts#L54).  If you want support for plsql as well, you'd need to add that to your own `files.associations` settings.

@betfix - Are you seeing any error out output for pgFormatter?  Here is how to check:
![image](https://user-images.githubusercontent.com/759811/91748933-645a3580-eb86-11ea-8def-e35986a1649f.png)

**Comment by woss** [comment]
Hi, for some reason i don't have it in the list. Check this out 
![nothing-here](https://user-images.githubusercontent.com/80440/91764347-6b5d6400-ebd7-11ea-90db-319b933309c4.png)
![Annotation 2020-08-31 221415](https://user-images.githubusercontent.com/80440/91764349-6bf5fa80-ebd7-11ea-8aa8-63e2c64e74e5.png)


Funny thing i have it working on the PC but not on the laptop. I'm using the VsCode with WSL2 debian distro

**Comment by bradymholt** [comment]
Make sure the associated format for the current file is either .sql or.pgsql (check on bottom right) and then attempt to format, _then_ look for output.

![CleanShot 2020-08-31 at 15 28 01](https://user-images.githubusercontent.com/759811/91765491-b60eba00-eb9e-11ea-8fb2-fe58fbd53ad9.png)


I'm not sure what is wrong with your setup but I've confirmed this works on other Windows installs.  It might be something specific to your installation.

**Comment by woss** [comment]
so with PLSQL at the bottom doesn't work? i just switched it to SQL and it worked. I guess i need to remap the PLSQL to SQL
