### ISSUE TITLE
Use Special Characters in "pgFormatter.placeholder"

### ISSUE THREAD

**Issue by lucasprograms** [bradymholt/vscode-pgFormatter#35]
- [X] This is not an issue related to formatting of SQL itself.  (For formatting problems, an [issue should be created in the pgFormatter repository](https://github.com/darold/pgFormatter)).
- [X] Perl is installed on my system and when I run `perl --version` from a terminal I get information about the version of Perl installed.

In an app we use the syntax `${ variable }` to pass arguments to sql queries. Currently, the `${` is formatted as `$ {`, which breaks the functionality.

I have attempted to provide `"${"`, `"\${"`, `"\\${"`, `"\$\{"`, and `"\\$\\{"` as the value for `"pgFormatter.placeholder"`. All of those break the formatter entirely. Providing some value like `"from"`, works as expected.

Is it possible to use special characters in the placeholder?

**Comment by bradymholt** [comment]
The `placeholder` option is passed straight through to pgFormatter.  You might want to ask about its usage or request a tweak over there: https://github.com/darold/pgFormatter.
