### ISSUE TITLE
No support for `--extra-function` config?

### ISSUE THREAD

**Issue by keithlayne** [bradymholt/vscode-pgFormatter#38]
I don't see a way to configure this, and I don't know if this extension will pick up a config file.  Both of these seem useful.

In my case, `pgFormatter` seems to format my functions as `schema.fn ()` with an extra space before the parens.  I guess that's not the end of the world, because AFAICT pg doesn't care,  but I don't like it.  Thoughts?

Seems probably pretty easy to add, and if you want I can look at doing so.

- [x] This is not an issue related to formatting of SQL itself.  (For formatting problems, an [issue should be created in the pgFormatter repository](https://github.com/darold/pgFormatter)).
- [x] Perl is installed on my system and when I run `perl --version` from a terminal I get information about the version of Perl installed.

**Comment by bradymholt** [comment]
Correct.  Not supported.  It would need to be added to https://github.com/bradymholt/psqlformat, if you want to submit a PR there.

**Comment by keithlayne** [comment]
See bradymholt/psqlformat#23
