### ISSUE TITLE
Formatting sql file results in an empty file

### ISSUE THREAD

**Issue by christianharke** [bradymholt/vscode-pgFormatter#4]
If I run `Format Document` command, this formatter empties the whole file. What am I doing wrong?

I am running vscode 1.19.2 on Fedora 27 with pgFormatter 1.3.0.

**Comment by brokenthorn** [comment]
This happens when you have configured `"pgFormatter.maxLength": 80` (or any other value). Could be related to pgFormatter, and not vscode-pgFormatter but I don't mind a few longer lines.

**Comment by christianharke** [comment]
I can't remember configuring that setting in any way... Unfortunately, I am unable to reproduce this issue, since I reinstalled my computer and am using the snappy package of vscode (slightly older version 1.19.1) on Ubuntu 17.10 now.

**Comment by galileo-pkm** [comment]
Just installed pgFormatter, same issue. 
Fedora 28, VS Code 1.23.1

**Comment by TuomoKareoja** [comment]
Same issue. Have not made any changes to default configurations.
Windows 10 (OS Build 17134.167) VS Code 1.25.1

**Comment by stepankuzmin** [comment]
Same here. macOS  10.13.6, VS Code 1.25.1, perl 5.18.2

**Comment by smabbutt** [comment]
Same problem - entire editor contents disappears. Freshly installed VS Code 1.25.1 on Windows 10, Perl 5.28.0.

**Comment by dewey** [comment]
Same here, only happens if I use the line length setting.

**Comment by barbalex** [comment]
Same here. Using Windows 10, vscode 1.28.2. Can't _not_ set `maxLength` as it is preset to 0

**Comment by bradymholt** [comment]
The `maxLength` setting gets sent to pgFormatter as `--maxlength` option and it _truncates_ the SQL statement after the number of specified characters.  This is not obvious and is unexpected.  I'm going to remove support for maxLength to prevent this from happening.  pgFormatter does not currently support formatting to a specified number of columns, which is what people who use this option expect it to do.

**Comment by nmummau** [comment]
@bradymholt with 1.6.2 now my SQL files are also being truncated...

**Comment by bradymholt** [comment]
Were they being truncated before, as well?  What settings do you have in place?

**Comment by bradymholt** [comment]
Thanks for the info @nmummau .  The issue was because I the vsCode `formatType` option was defaulted as false and a bug in psqlformat was passing this arg in in correctly.  Fixed here:  https://github.com/bradymholt/psqlformat/commit/43212a8029de7fcdae8000882e0ebb4af1af7d58

Version 1.6.4 should fix this.

**Comment by nmummau** [comment]
1.6.4 solved my issues. Thank you.
