### ISSUE TITLE
Format Tagged Template Strings in JS / TS?

### ISSUE THREAD

**Issue by karlhorky** [bradymholt/vscode-pgFormatter#40]
- [x] This is not an issue related to formatting of SQL itself.  (For formatting problems, an [issue should be created in the pgFormatter repository](https://github.com/darold/pgFormatter)).
- [x] Perl is installed on my system and when I run `perl --version` from a terminal I get information about the version of Perl installed.

Hi there. First of all, thanks for your work on this extension, looks cool!

I was wondering whether you would be open to formatting template strings with SQL in JavaScript / TypeScript, such as the following example:

```js
const users = sql`
  SELECT
    first_name,
    last_name
  FROM
    users;
`;
```

**Comment by karlhorky** [comment]
Oh wait, just looking a bit more through issues, there seems to be this issue from @bradleyayers which seems to go in a similar direction.

@bradymholt does this mean that you're not open to this feature?

**Comment by bradymholt** [comment]
@karlhorky Thanks! Are you offering to work on this feature and wanting to know if I'm open to it or just requesting this feature?

**Comment by karlhorky** [comment]
If I had time right now, I'd love to work on it - but not sure when I would get around to it.

If you don't have bandwidth yourself but are open to accepting a PR, what about just tagging it as `help-wanted` and leaving it open?

**Comment by bradymholt** [comment]
@karlhorky - I appreciate the suggestion but would prefer to close it out as I like to use issues for bugs and not feature requests.  I get satisfaction in 0 issues opened 😄 .  I surely support contributions to the library but I wouldn't consider this particular feature as a current priority.

**Comment by karlhorky** [comment]
Ok, well at least it is documented here that you'd be open to it, in case anyone who has the bandwidth to contribute this fix would search the issues. Thanks for the feedback.
