### ISSUE TITLE
Consider publishing to open-vsx.org

### ISSUE THREAD

**Issue by madflow** [bradymholt/vscode-pgFormatter#41]
- [x] This is not an issue related to formatting of SQL itself.  (For formatting problems, an [issue should be created in the pgFormatter repository](https://github.com/darold/pgFormatter)).
- [x] Perl is installed on my system and when I run `perl --version` from a terminal I get information about the version of Perl installed.

Please consider publishing this extensions to  open-vsx.org.

* https://open-vsx.org/
* https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

> What is Open VSX?
> The Open VSX Registry offers a community driven, fully open platform for publishing VS Code extensions. The Registry is built on Eclipse Open VSX, which is an open source project hosted at the Eclipse Foundation.
> Open VSX is integrated into multiple software applications that support VS Code extensions. There is strong demand for a fully open alternative to the Visual Studio Marketplace, and with hundreds of great extensions already available, it is the intent of the Eclipse Foundation to enable continued and accelerated growth.

**Comment by bradymholt** [comment]
Thanks for the suggestion but I'd prefer to only publish to VS Marketplace at this time.
