### ISSUE TITLE
Use settings from .editorconfig as default identation style

### ISSUE THREAD

**Issue by luukvhoudt** [bradymholt/vscode-pgFormatter#46]
Is it possible to add a feature what allows user to override the default pgFormatter settings with a `.editorconfig` file?

For example, consider the following `.editorconfig` file:
```
[*.sql]
indent_size = 4
indent_style = tab
```

This would result in the following settings:
```js
pgFormatter.spaces = 4;
pgFormatter.tabs = true;
```

**Comment by bradymholt** [comment]
I'd welcome a PR for this.  I am going to close for now.
