### ISSUE TITLE
"user" word always converted to uppercase

### ISSUE THREAD

**Issue by lamualfa** [bradymholt/vscode-pgFormatter#47]
- [x] This is not an issue related to formatting of SQL itself.  (For formatting problems, an [issue should be created in the pgFormatter repository](https://github.com/darold/pgFormatter)).
- [x] Perl is installed on my system and when I run `perl --version` from a terminal I get information about the version of Perl installed.

<hr/>

## Problems

**Example when using `CREATE TABLE`**

```sql
CREATE TABLE IF NOT EXISTS user (
    id varchar(21) PRIMARY KEY
);
```

The `user` word will be converted to be uppercase after formatting using this extension:

```sql
CREATE TABLE IF NOT EXISTS USER (
    id varchar(21) PRIMARY KEY
);
```

<hr/>

Example when using `REFERENCES user(id)` :

```sql
CREATE TABLE IF NOT EXISTS account (
    id varchar(21) PRIMARY KEY,
    identity TEXT NOT NULL,
    user_id varchar(21) FOREIGN KEY REFERENCES user(id),
    type account_types NOT NULL,
    provider account_providers,
    provider_data jsonb
);
```

The `user` word will be converted to be uppercase after formatting using this extension:

```sql
CREATE TABLE IF NOT EXISTS account (
    id varchar(21) PRIMARY KEY,
    identity TEXT NOT NULL,
    user_id varchar(21) FOREIGN KEY REFERENCES USER (id),
    type account_types NOT NULL,
    provider account_providers,
    provider_data jsonb
);
```

## Screenshot

**Before**

![image](https://user-images.githubusercontent.com/39755201/143253370-7929f7fc-2f26-4872-9727-18168d63c70e.png)

**After**

![image](https://user-images.githubusercontent.com/39755201/143253441-3bff2319-a353-42eb-aceb-adec325b2038.png)

**Comment by bradymholt** [comment]
Can you open an issue an [pgFormatter repo](https://github.com/darold/pgFormatter) instead?

**Comment by lamualfa** [comment]
> Can you open an issue an [pgFormatter repo](https://github.com/darold/pgFormatter) instead?

Oh, i am sorry.
