### ISSUE TITLE
Formatter for upper case not correct working

### ISSUE THREAD

**Issue by Cheban1996** [bradymholt/vscode-pgFormatter#67]
```
CREATE TYPE user_type AS ENUM(
	'main',
	'sub'
);

CREATE TABLE users(
	id serial PRIMARY KEY,
	email character(64) NOT NULL UNIQUE CHECK (LENGTH(email) = 64),
	created_at timestamp NOT NULL DEFAULT NOW(),
	updated_at timestamp NOT NULL DEFAULT NOW()
);
```
Why formatter not to upper case for serial, character and timestamp
if my settings
```
    "pgFormatter.functionCase": "uppercase",
    "pgFormatter.keywordCase": "uppercase",
```

**Comment by bradymholt** [comment]
For formatting problems, an [issue should be created in the pgFormatter repository](https://github.com/darold/pgFormatter).

**Comment by Cheban1996** [comment]
> For formatting problems, an [issue should be created in the pgFormatter repository](https://github.com/darold/pgFormatter).

No, beacause if I use https://sqlformat.darold.net/ is alright
<img width="291" alt="image" src="https://github.com/bradymholt/vscode-pgFormatter/assets/11075696/549485cb-c43d-414e-9eec-3a6a2d1afe78">

Please implement Datatypes
@bradymholt  thanks

**Comment by Cheban1996** [comment]
```
if (config.datatypeCase != null) {
      formattingOptions.keywordCase = CaseOptionEnum[<keyof typeof CaseOptionEnum>config.datatypeCase];
    }
```
need add in src/extention.ts

```
"pgFormatter.datatypeCase": {
          "type": "string",
          "default": "unchanged",
          "enum": [
            "unchanged",
            "lowercase",
            "uppercase",
            "capitalize"
          ],
          "description": "Case of the datatype names"
        },
  ```
add in package.json

**Comment by bradymholt** [comment]
Implemented in https://github.com/bradymholt/vscode-pgFormatter/releases/tag/v1.27.0
