### ISSUE TITLE
Doesn't support the `--placeholder` option

### ISSUE THREAD

**Issue by kstrauser** [bradymholt/vscode-pgFormatter#7]
The [README for pgFormatter](https://github.com/darold/pgFormatter) says:

> Prevent replacing code snippets
> Using -p or --placeholder command line option it is possible to keep
> code untouched by pgFormatter in your SQL queries. For example, in query
> like:
> 
>             SELECT * FROM projects WHERE projectnumber
>                     IN <<internalprojects>> AND username = <<loginname>>;
> 
> you may want pgFormatter to not interpret << and >> as bit-shift
> keywords and modify your code snippsets.

Much of my SQL work in vscode involves writing templates that are expanded later, and I'd love for vscode-pgFormatter to support that option so that I could use it to make my templates look pretty.

Thanks so much for this plugin, BTW!

**Comment by bradymholt** [comment]
I don't have time to do this currently but would welcome a PR.
