### ISSUE TITLE
Each Stored Procedure Parameter on their own line

### ISSUE THREAD

**Issue by MatthewPosgate** [bradymholt/vscode-pgFormatter#73]
Great tool thanks.
I would love it if there was an option to allow parameters in stored procedures and functions to each be on their own line.
so this:
   IN _name text,
   IN _greeting text,
   IN _contact_type text

instead of:
  IN _name text, IN _greeting text, IN _contact_type text

**Comment by bradymholt** [comment]
@MatthewPosgate - https://github.com/darold/pgFormatter This extensions uses https://github.com/darold/pgFormatter so that would be the best place to submit a specific formatting feature request.
