### ISSUE TITLE
Feature request: support for template literals

### ISSUE THREAD

**Issue by cabello** [bradymholt/vscode-pgFormatter#75]
Hello there 👋 

Thank you for sharing this lovely extension with us. 💜 

I use this project for writing typed SQL in my node.js projects: https://pgtyped.dev/docs/ts-file-intro

And as you can see in the sample page you write the SQL code using template literals:

```
import { sql } from '@pgtyped/runtime';
import { ISelectUserIdsQuery } from './queries.types.ts';

export const selectUserIds = sql<
  ISelectUserIdsQuery
>`select id, age from users where id = $id and age = $age`;
```

I would love to find a way to configure this extension to format SQL code within these snippets.

Something like this regex to pull the SQL query: 

```
const sqlRegex = /sql\s*`([^`]+)`/g;
```

This way the extension would format not only SQL files but also TS-in-SQL files.

Do you think that would be out of scope for this?

Thank you again. 🙇

**Comment by bradymholt** [comment]
> Do you think that would be out of scope for this?

Yes probably so, since the extension would have to have special logic to work with these snippets.  I think creating another extension that works with pgTypes and uses https://github.com/bradymholt/psqlformat for formatting would probably be the best way to go.
